const CONSTANTS = {
    FRAMES_PER_GAME_HOUR: 150,
    SPREAD_RATE_PER_DAY: 80000,
    BIT_ASSEMBLY_COST: 25000,
    MOTOR_COST: 15000,
    TRIP_SPEED_FT_PER_HR: 20000,
    KICK_TIME_PER_1000FT: 1,
    NPV_LOSS_RATE: 1000,
    LOG_INTERVAL: 10,
    MAX_LOG_POINTS: 380,
    DRILL_Y: 300,
    SLIDING_ROP_FACTOR: 0.2,
    SLIDING_STEER_SPEED: 1.2, // Increased from 0.15
    ROTATE_DRIFT_SPEED: 0.15,
    ROTATE_DRIFT_CHANGE_INTERVAL: 180,
    
    // Motor/Diff Pressure Constants
    MOTOR_MAX_DP: 2000,
    MOTOR_RECOMMENDED_DP: 1600,
    MOTOR_SPIKE_THRESHOLD: 0.8,
    MOTOR_MAX_SPIKES: 20,
    MOTOR_MIN_SPIKES_TO_FAIL: 15,
    DP_BASE_MULTIPLIER: 30,
    DP_HARDNESS_DIVISOR: 1.5,
    MOTOR_STALL_DP: 1900,
    
    // Mud Loss Constants
    MUD_COST_PER_BBL: 100,
    LCM_COST_PER_LB: 2,
    
    // Limits
    MAX_MUD_WEIGHT: 17.0,
    MAX_WOB: 80
};
